CREATE TABLE USUARIO (
    ID PRIMARY KEY,
    NOMBRE Y APELLIDOS VARCHAR(100),
    USERNAME VARCHAR(50),
    CORREO VARCHAR(200),
    CLAVE CIFRADA VARCHAR(50),
)

CREATE TABLE PROFE (
    ID_PROFE PRIMARY KEY,
    NOMBRE Y APELLIDOS VARCHAR(100),
    USERNAME VARCHAR(100),
    CORREO VARCHAR(500),
    CLAVE_CIFRADA VARCHAR(50),
)

CREATE TABLE CURSOS (
    ID_CURSOS PRIMARY KEY VARCHAR(100),
    ID-PROFE INT,  
    FOREIGN KEY (ID-PROFE) REFERENCES PROFE (ID_PROFE),
    NOMBRE VARCHAR(100),
)

CREATE TABLE EVALUA (
    ID_ALUMNO INT,
    FOREING KEY (ID_ALUMNO) REFERENCES EVALUA (ID_ALUMNO),
    ID-ALUMNO INT,
    FOREING KEY (ID-ALUMNO) REFERENCES EVALUA (ID-ALUMNO),
    EVALUADOR INT,
    FOREING KEY (EVALUADOR) REFERENCES EVALUA (EVALUADOR),
    EVALUADO INT,
    FOREING KEY (EVALUADO) REFERENCES EVALUA (EVALUADO),
    PUNTOS INT,
    FOREING KEY (PUNTOS) REFERENCES EVALUA (PUNTOS),
    SOFTSKILLS INT,
    FOREING KEY (SOFTSKILLS) REFERENCES EVALUA (SOFTSKILLS),
)

CREATE TABLE ALUMNO_CURSOS (
    ID_USUARIO INT,         
    FOREIGN KEY (ID-ALUMNO) REFERENCES ALUMNO(ID_ALUMNO),
    ID_CURSO INT,           
    FOREIGN KEY (ID-CURSO) REFERENCES CURSOS(ID_CURSO),
    ACEPTADO INT,
    CODICIA INT,
    PROGRESO INT,
)

CREATE TABLE OBJETOS(
    ID PRIMARY KEY VARCHAR(100),
    ID_ITEM VARCHAR(100),
    CANTIDAD VARCHAR(100),
    ID_CURSO INT,
    FOREIGN KEY (ID-CURSO) REFERENCES CURSOS(ID_CURSO),

)

CREATE TABLE TIERRAS (
    POSICION PRIMARY KEY INT,
    TIPO_TERRENO INT,
    ID_CURSO INT,                                    
    FOREIGN KEY (ID-CURSO) REFERENCES CURSOS(ID_CURSO),

)

CREATE TABLE NOTIFICACIONES (
    ID_NOTIF PRIMARY KEY INT,
    ID_ALUMNO INT,                                   
    FOREIGN KEY (ID-ALUMNO) REFERENCES ALUMNO(ID_ALUMNO),
    ID_CURSO INT,                                    
    FOREIGN KEY (ID-CURSO) REFERENCES CURSOS(ID_CURSO),
    TIPO INT,
    FECHA VARCHAR(100),
    VISTA? INT,
)

CREATE TABLE RANKING (
    ID_RANKING PRIMARY KEY INT,
    ID_PROFE INT,                             
    FOREIGN KEY (ID-PROFE) REFERENCES PROFE(ID_PROFE),
    ID_CURSO INT,                            
    FOREIGN KEY (ID-CURSO) REFERENCES CURSOS(ID_CURSO),
    ID_TAREA INT,                            
    FOREIGN KEY (ID_TAREA) REFERENCES TAREA(ID_TAREA),
    PUNTUACION TOTAL VARCHAR(100),
    
)

CREATE TABLE ALUMNO_TAREA (
    ID_ALUMNO INT,                            
    FOREIGN KEY (ID-ALUMNO) REFERENCES ALUMNO(ID_ALUMNO),
    ID_TAREA INT,                              
    FOREIGN KEY (ID_TAREA) REFERENCES TAREA(ID_TAREA),
    NOTA VARCHAR(100),
)

INSERT INTO USUARIO (ID, NOMBRE Y APELLIDOS, USERNAME, CORREO, CLAVE CIFRADA) VALUES
(1, 'Juan Perez', 'jperez', 'jperez@example.com', 'password123'),
(2, 'Maria Lopez', 'mlopez', 'mlopez@example.com', 'securepwd456'),

INSERT INTO PROFE (ID_PROFE, NOMBRE Y APELLIDOS, USERNAME, CORREO, CLAVE_CIFRADA) VALUES
(1, 'Carlos Martinez', 'cmartinez', 'cmartinez@example.com', 'teacherpass789'),
(2, 'Ana Rodriguez', 'arodriguez', 'arodriguez@example.com', 'teach2020'),

INSERT INTO CURSOS (ID_CURSOS, ID-PROFE, NOMBRE) VALUES
('C001', 1, 'Matemáticas Avanzadas'),
('C002', 2, 'Historia del Arte'),

INSERT INTO EVALUA (ID_ALUMNO, ID-ALUMNO, EVALUADOR, EVALUADO, PUNTOS, SOFTSKILLS) VALUES
(1, 2, 3, 4, 90, 85),
(2, 3, 4, 5, 80, 75),

INSERT INTO ALUMNO_CURSOS (ID_USUARIO, ID_CURSO, ACEPTADO, CODICIA, PROGRESO) VALUES
(1, 1, 1, 0, 50),
(2, 2 ,0 ,1 ,25),

INSERT INTO OBJETOS (ID_ITEM , CANTIDAD , ID_CURSO) VALUES
('I001', '10 unidades', 1),
('I002', '5 unidades', 2),

INSERT INTO TIERRAS (POSICION , TIPO_TERRENO , ID_CURSO) VALUES
(1 , 3 , 1),
(2 , 2 , 2),

INSERT INTO NOTIFICACIONES (ID_ALUMNO , ID_CURSO , TIPO , FECHA , VISTA?) VALUES
(1 , 1 , 1 , '2024-03-14' , 0),
(2 , 2 , 2 , '2024-03-15' , 1),

INSERT INTO RANKING (ID_PROFE , ID_CURSO , ID_TAREA , PUNTUACION TOTAL) VALUES
(1 , 1 , 1 ,'10'),
(2 , 2 , 2 ,'3'),

INSERT INTO ALUMNO_TAREA (ID_ALUMNO , ID_TAREA , NOTA) VALUES
(1 , 1 ,'Excelente trabajo!'),
(2 , 2 ,'Puede mejorar en la presentación.'),

--Consulta 1: Crear cuenta  

--Consulta 2: Log in como Alumno

--Consulta 3: Cambiar icono

--Consulta 4:Crear cuenta como profesor 

--Consulta 5:Log in como profesor

--Consulta 6:Crear curso
